// The OpenNext build creates this module before Wrangler bundles the custom
// entrypoint. Reusing its fetch handler keeps one finfold-app Worker while
// adding Queue and scheduled handlers.
// @ts-expect-error Generated by `opennextjs-cloudflare build`.
import openNextHandler from "./.open-next/worker.js";
import type { GenerationJobMessage } from "./lib/generation-jobs";
import { INTERNAL_WORKER_SECRET_HEADER } from "./lib/internal-worker-auth";
import {
  runWorkerSchedule,
  type WorkerScheduledEvent
} from "./lib/worker-scheduling";
import { isEnglishPathname } from "./lib/locale-routing";

const DEFAULT_GENERATION_QUEUE_NAME = "finfold-generation-jobs";
const DEFAULT_GENERATION_DLQ_NAME = "finfold-generation-jobs-dlq";
const MAX_INTERNAL_RESPONSE_BYTES = 64 * 1024;
const SCHEDULE_INTERNAL_ROUTE_TIMEOUT_MS = 60_000;

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

type QueueMessage<Body> = {
  readonly id: string;
  readonly body: Body;
  readonly attempts: number;
  ack(): void;
  retry(options?: { delaySeconds?: number }): void;
};

type QueueBatch<Body> = {
  readonly queue: string;
  readonly messages: readonly QueueMessage<Body>[];
};

type FinfoldWorkerHandler = {
  fetch: typeof openNextHandler.fetch;
  queue(
    batch: QueueBatch<GenerationJobMessage>,
    env: CloudflareEnv,
    ctx: WorkerExecutionContext
  ): Promise<void>;
  scheduled(
    event: WorkerScheduledEvent,
    env: CloudflareEnv,
    ctx: WorkerExecutionContext
  ): Promise<void>;
};

type HtmlElement = {
  setAttribute(name: string, value: string): void;
};

type HtmlRewriterInstance = {
  on(
    selector: string,
    handlers: { element(element: HtmlElement): void }
  ): HtmlRewriterInstance;
  transform(response: Response): Response;
};

type HtmlRewriterConstructor = new () => HtmlRewriterInstance;

/**
 * Next's shared root layout stays static and therefore cannot read the route
 * pathname while it renders. Correct the root language at the Worker edge so
 * English pages keep their pre-rendered HTML and still arrive as lang="en".
 */
async function fetchWithLocalizedDocumentLanguage(
  request: Parameters<typeof openNextHandler.fetch>[0],
  env: Parameters<typeof openNextHandler.fetch>[1],
  ctx: Parameters<typeof openNextHandler.fetch>[2]
): Promise<Response> {
  const response = await openNextHandler.fetch(request, env, ctx);
  const pathname = new URL(request.url).pathname;
  const contentType = response.headers.get("content-type") ?? "";

  if (!isEnglishPathname(pathname) || !contentType.includes("text/html")) {
    return response;
  }

  const HtmlRewriter = (
    globalThis as typeof globalThis & { HTMLRewriter?: HtmlRewriterConstructor }
  ).HTMLRewriter;
  if (!HtmlRewriter) return response;

  return new HtmlRewriter()
    .on("html", {
      element(element) {
        element.setAttribute("lang", "en");
      }
    })
    .transform(response);
}

type QueueNameEnvironment = {
  readonly GENERATION_QUEUE_NAME?: string;
  readonly GENERATION_DLQ_NAME?: string;
};

function configuredQueueNames(env: CloudflareEnv): {
  generation: string;
  deadLetter: string;
} {
  const names = env as CloudflareEnv & QueueNameEnvironment;
  return {
    generation:
      names.GENERATION_QUEUE_NAME?.trim() || DEFAULT_GENERATION_QUEUE_NAME,
    deadLetter:
      names.GENERATION_DLQ_NAME?.trim() || DEFAULT_GENERATION_DLQ_NAME
  };
}

type WorkerOutcome = {
  status: "succeeded" | "partial_success" | "terminal" | "busy" | "retry" | "failed";
  retryable?: boolean;
  error?: string;
};

async function callInternalRoute(
  path: string,
  env: CloudflareEnv,
  ctx: WorkerExecutionContext,
  body: unknown,
  extraHeaders?: Record<string, string>,
  timeoutMs?: number
): Promise<Response> {
  const abortController = timeoutMs ? new AbortController() : null;
  const request = new Request(`https://internal.finfold.app${path}`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      [INTERNAL_WORKER_SECRET_HEADER]: env.GENERATION_WORKER_SECRET,
      ...extraHeaders
    },
    body: JSON.stringify(body),
    ...(abortController ? { signal: abortController.signal } : {})
  });
  const routeCall = openNextHandler.fetch(request, env, ctx);
  if (!abortController || !timeoutMs) {
    return routeCall;
  }

  let timeoutId: ReturnType<typeof setTimeout> | null = null;
  const timeout = new Promise<never>((_, reject) => {
    timeoutId = setTimeout(() => {
      abortController.abort();
      reject(new Error("Internal scheduled route timed out."));
    }, timeoutMs);
  });
  try {
    return await Promise.race([routeCall, timeout]);
  } finally {
    if (timeoutId !== null) clearTimeout(timeoutId);
  }
}

async function readBoundedInternalResponse(response: Response): Promise<string> {
  if (!response.body) return "";
  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let received = 0;
  let text = "";
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    received += value.byteLength;
    if (received > MAX_INTERNAL_RESPONSE_BYTES) {
      await reader.cancel("Internal response exceeded its bounded contract.");
      throw new Error("Internal generation response exceeded 64 KiB.");
    }
    text += decoder.decode(value, { stream: true });
  }
  return text + decoder.decode();
}

function parseWorkerOutcome(stream: string): WorkerOutcome | null {
  for (const block of stream.split("\n\n")) {
    const lines = block.split("\n");
    if (lines.find((line) => line === "event: worker") === undefined) {
      continue;
    }
    const data = lines.find((line) => line.startsWith("data: "));
    if (!data) return null;
    try {
      const parsed = JSON.parse(data.slice(6)) as Partial<WorkerOutcome>;
      if (
        parsed.status === "succeeded" ||
        parsed.status === "partial_success" ||
        parsed.status === "terminal" ||
        parsed.status === "busy" ||
        parsed.status === "retry" ||
        parsed.status === "failed"
      ) {
        return parsed as WorkerOutcome;
      }
    } catch {
      return null;
    }
  }
  return null;
}

async function handleGenerationMessage(
  message: QueueMessage<GenerationJobMessage>,
  env: CloudflareEnv,
  ctx: WorkerExecutionContext
): Promise<void> {
  try {
    const response = await callInternalRoute(
      "/api/generate",
      env,
      ctx,
      message.body,
      { "x-finfold-queue-attempt": String(message.attempts) }
    );
    const body = await readBoundedInternalResponse(response);
    const outcome = parseWorkerOutcome(body);
    if (!response.ok || !outcome) {
      console.error(
        JSON.stringify({
          event: "generation_queue_invalid_response",
          message_id: message.id,
          status: response.status
        })
      );
      message.retry({ delaySeconds: 60 });
      return;
    }
    if (outcome.status === "retry") {
      message.retry({
        delaySeconds: Math.min(30 * 2 ** Math.max(message.attempts - 1, 0), 900)
      });
      return;
    }
    message.ack();
  } catch (error) {
    console.error(
      JSON.stringify({
        event: "generation_queue_consumer_error",
        message_id: message.id,
        attempt: message.attempts,
        error: error instanceof Error ? error.message : String(error)
      })
    );
    message.retry({
      delaySeconds: Math.min(30 * 2 ** Math.max(message.attempts - 1, 0), 900)
    });
  }
}

async function handleDeadLetterMessage(
  message: QueueMessage<GenerationJobMessage>,
  env: CloudflareEnv,
  ctx: WorkerExecutionContext
): Promise<void> {
  try {
    const response = await callInternalRoute(
      "/api/internal/generation/dead-letter",
      env,
      ctx,
      {
        message: message.body,
        error: "Generation exhausted its Cloudflare Queue retries."
      }
    );
    if (!response.ok) {
      message.retry({ delaySeconds: 300 });
      return;
    }
    await response.body?.cancel();
    message.ack();
  } catch (error) {
    console.error(
      JSON.stringify({
        event: "generation_dlq_consumer_error",
        message_id: message.id,
        error: error instanceof Error ? error.message : String(error)
      })
    );
    message.retry({ delaySeconds: 300 });
  }
}

export default {
  fetch: fetchWithLocalizedDocumentLanguage,

  async queue(batch, env, ctx) {
    const queueNames = configuredQueueNames(env);
    for (const message of batch.messages) {
      if (batch.queue === queueNames.deadLetter) {
        await handleDeadLetterMessage(message, env, ctx);
      } else if (batch.queue === queueNames.generation) {
        await handleGenerationMessage(message, env, ctx);
      } else {
        console.error(
          JSON.stringify({
            event: "generation_queue_unknown_source",
            queue: batch.queue,
            message_id: message.id
          })
        );
        message.ack();
      }
    }
  },

  async scheduled(event, env, ctx) {
    await runWorkerSchedule(
      event,
      (path, body) => callInternalRoute(
        path,
        env,
        ctx,
        body,
        undefined,
        SCHEDULE_INTERNAL_ROUTE_TIMEOUT_MS
      ),
      console,
      {
        signalDiscoveryEnabled: process.env.SIGNAL_DISCOVERY_ENABLED === "true",
        wechatPublishingEnabled:
          env.WECHAT_COMPONENT_ENABLED === "true"
          && env.WECHAT_DRAFT_PUBLISHING_ENABLED === "true",
        xPublishingEnabled: env.X_PUBLISHING_ENABLED === "true",
        xPipelineEnabled: env.X_PIPELINE_ENABLED === "true",
        contentPipelineEnabled: env.CONTENT_PIPELINE_ENABLED === "true"
      }
    );
  }
} satisfies FinfoldWorkerHandler;
