/* eslint-disable */
/** GENERATED FILE — emergency Lucide fallbacks for every Finfold icon. */

import {
  Activity as LucideActivity,
  AlertCircle as LucideAlertCircle,
  AlertTriangle as LucideAlertTriangle,
  ArrowBigDown as LucideArrowBigDown,
  ArrowBigUp as LucideArrowBigUp,
  ArrowDown as LucideArrowDown,
  ArrowDownRight as LucideArrowDownRight,
  ArrowLeft as LucideArrowLeft,
  ArrowRight as LucideArrowRight,
  ArrowUp as LucideArrowUp,
  ArrowUpRight as LucideArrowUpRight,
  AtSign as LucideAtSign,
  Award as LucideAward,
  BadgeCheck as LucideBadgeCheck,
  Ban as LucideBan,
  BarChart3 as LucideBarChart3,
  Bookmark as LucideBookmark,
  BookOpenText as LucideBookOpenText,
  Bot as LucideBot,
  Braces as LucideBraces,
  Brain as LucideBrain,
  BrainCircuit as LucideBrainCircuit,
  BriefcaseBusiness as LucideBriefcaseBusiness,
  Bug as LucideBug,
  Building2 as LucideBuilding2,
  CalendarDays as LucideCalendarDays,
  Camera as LucideCamera,
  Check as LucideCheck,
  CheckCircle2 as LucideCheckCircle2,
  ChevronDown as LucideChevronDown,
  ChevronRight as LucideChevronRight,
  ChevronUp as LucideChevronUp,
  Circle as LucideCircle,
  CircleAlert as LucideCircleAlert,
  CircleDot as LucideCircleDot,
  CircleDotDashed as LucideCircleDotDashed,
  CircleGauge as LucideCircleGauge,
  CircleHelp as LucideCircleHelp,
  CirclePlus as LucideCirclePlus,
  Clipboard as LucideClipboard,
  ClipboardList as LucideClipboardList,
  ClipboardPaste as LucideClipboardPaste,
  Clock as LucideClock,
  Clock3 as LucideClock3,
  Code as LucideCode,
  Coffee as LucideCoffee,
  Coins as LucideCoins,
  Compass as LucideCompass,
  Copy as LucideCopy,
  CreditCard as LucideCreditCard,
  Database as LucideDatabase,
  DatabaseZap as LucideDatabaseZap,
  Download as LucideDownload,
  Expand as LucideExpand,
  ExternalLink as LucideExternalLink,
  Eye as LucideEye,
  Facebook as LucideFacebook,
  FileCode2 as LucideFileCode2,
  FileJson as LucideFileJson,
  FileSpreadsheet as LucideFileSpreadsheet,
  FileStack as LucideFileStack,
  FileText as LucideFileText,
  Film as LucideFilm,
  Flame as LucideFlame,
  FlaskConical as LucideFlaskConical,
  Gauge as LucideGauge,
  Gift as LucideGift,
  Globe as LucideGlobe,
  Globe2 as LucideGlobe2,
  Hash as LucideHash,
  Heart as LucideHeart,
  History as LucideHistory,
  Home as LucideHome,
  Image as LucideImage,
  ImageIcon as LucideImageIcon,
  ImagePlus as LucideImagePlus,
  Images as LucideImages,
  Info as LucideInfo,
  Instagram as LucideInstagram,
  KeyRound as LucideKeyRound,
  Languages as LucideLanguages,
  Layers as LucideLayers,
  Layers3 as LucideLayers3,
  LayoutTemplate as LucideLayoutTemplate,
  Lightbulb as LucideLightbulb,
  Link2 as LucideLink2,
  Loader2 as LucideLoader2,
  Lock as LucideLock,
  LockKeyhole as LucideLockKeyhole,
  LogIn as LucideLogIn,
  LogOut as LucideLogOut,
  Mail as LucideMail,
  MapPin as LucideMapPin,
  Menu as LucideMenu,
  MessageCircle as LucideMessageCircle,
  MessageSquare as LucideMessageSquare,
  MessageSquareWarning as LucideMessageSquareWarning,
  Mic as LucideMic,
  Minus as LucideMinus,
  Moon as LucideMoon,
  MoreHorizontal as LucideMoreHorizontal,
  Palette as LucidePalette,
  PanelRight as LucidePanelRight,
  Paperclip as LucidePaperclip,
  Pencil as LucidePencil,
  PenLine as LucidePenLine,
  PlugZap as LucidePlugZap,
  Plus as LucidePlus,
  Quote as LucideQuote,
  Radar as LucideRadar,
  Radio as LucideRadio,
  RadioTower as LucideRadioTower,
  ReceiptText as LucideReceiptText,
  RefreshCcw as LucideRefreshCcw,
  RefreshCw as LucideRefreshCw,
  Repeat2 as LucideRepeat2,
  Rocket as LucideRocket,
  RotateCcw as LucideRotateCcw,
  Save as LucideSave,
  ScanLine as LucideScanLine,
  Search as LucideSearch,
  Send as LucideSend,
  Settings as LucideSettings,
  Share2 as LucideShare2,
  Shield as LucideShield,
  ShieldAlert as LucideShieldAlert,
  ShieldCheck as LucideShieldCheck,
  SlidersHorizontal as LucideSlidersHorizontal,
  Smartphone as LucideSmartphone,
  Sparkles as LucideSparkles,
  Square as LucideSquare,
  Star as LucideStar,
  Store as LucideStore,
  Sun as LucideSun,
  Target as LucideTarget,
  ThumbsDown as LucideThumbsDown,
  ThumbsUp as LucideThumbsUp,
  TicketCheck as LucideTicketCheck,
  Trash2 as LucideTrash2,
  TrendingUp as LucideTrendingUp,
  TriangleAlert as LucideTriangleAlert,
  Unlink as LucideUnlink,
  Upload as LucideUpload,
  User as LucideUser,
  UserPlus as LucideUserPlus,
  UserRound as LucideUserRound,
  Users as LucideUsers,
  UsersRound as LucideUsersRound,
  Wand2 as LucideWand2,
  WandSparkles as LucideWandSparkles,
  Wrench as LucideWrench,
  X as LucideX,
  XCircle as LucideXCircle,
  Zap as LucideZap
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const lucideFallbacks = {
  Activity: LucideActivity,
  AlertCircle: LucideAlertCircle,
  AlertTriangle: LucideAlertTriangle,
  ArrowBigDown: LucideArrowBigDown,
  ArrowBigUp: LucideArrowBigUp,
  ArrowDown: LucideArrowDown,
  ArrowDownRight: LucideArrowDownRight,
  ArrowLeft: LucideArrowLeft,
  ArrowRight: LucideArrowRight,
  ArrowUp: LucideArrowUp,
  ArrowUpRight: LucideArrowUpRight,
  AtSign: LucideAtSign,
  Award: LucideAward,
  BadgeCheck: LucideBadgeCheck,
  Ban: LucideBan,
  BarChart3: LucideBarChart3,
  Bookmark: LucideBookmark,
  BookOpenText: LucideBookOpenText,
  Bot: LucideBot,
  Braces: LucideBraces,
  Brain: LucideBrain,
  BrainCircuit: LucideBrainCircuit,
  BriefcaseBusiness: LucideBriefcaseBusiness,
  Bug: LucideBug,
  Building2: LucideBuilding2,
  CalendarDays: LucideCalendarDays,
  Camera: LucideCamera,
  Check: LucideCheck,
  CheckCircle2: LucideCheckCircle2,
  ChevronDown: LucideChevronDown,
  ChevronRight: LucideChevronRight,
  ChevronUp: LucideChevronUp,
  Circle: LucideCircle,
  CircleAlert: LucideCircleAlert,
  CircleDot: LucideCircleDot,
  CircleDotDashed: LucideCircleDotDashed,
  CircleGauge: LucideCircleGauge,
  CircleHelp: LucideCircleHelp,
  CirclePlus: LucideCirclePlus,
  Clipboard: LucideClipboard,
  ClipboardList: LucideClipboardList,
  ClipboardPaste: LucideClipboardPaste,
  Clock: LucideClock,
  Clock3: LucideClock3,
  Code: LucideCode,
  Coffee: LucideCoffee,
  Coins: LucideCoins,
  Compass: LucideCompass,
  Copy: LucideCopy,
  CreditCard: LucideCreditCard,
  Database: LucideDatabase,
  DatabaseZap: LucideDatabaseZap,
  Download: LucideDownload,
  Expand: LucideExpand,
  ExternalLink: LucideExternalLink,
  Eye: LucideEye,
  Facebook: LucideFacebook,
  FileCode2: LucideFileCode2,
  FileJson: LucideFileJson,
  FileSpreadsheet: LucideFileSpreadsheet,
  FileStack: LucideFileStack,
  FileText: LucideFileText,
  Film: LucideFilm,
  Flame: LucideFlame,
  FlaskConical: LucideFlaskConical,
  Gauge: LucideGauge,
  Gift: LucideGift,
  Globe: LucideGlobe,
  Globe2: LucideGlobe2,
  Hash: LucideHash,
  Heart: LucideHeart,
  History: LucideHistory,
  Home: LucideHome,
  Image: LucideImage,
  ImageIcon: LucideImageIcon,
  ImagePlus: LucideImagePlus,
  Images: LucideImages,
  Info: LucideInfo,
  Instagram: LucideInstagram,
  KeyRound: LucideKeyRound,
  Languages: LucideLanguages,
  Layers: LucideLayers,
  Layers3: LucideLayers3,
  LayoutTemplate: LucideLayoutTemplate,
  Lightbulb: LucideLightbulb,
  Link2: LucideLink2,
  Loader2: LucideLoader2,
  Lock: LucideLock,
  LockKeyhole: LucideLockKeyhole,
  LogIn: LucideLogIn,
  LogOut: LucideLogOut,
  Mail: LucideMail,
  MapPin: LucideMapPin,
  Menu: LucideMenu,
  MessageCircle: LucideMessageCircle,
  MessageSquare: LucideMessageSquare,
  MessageSquareWarning: LucideMessageSquareWarning,
  Mic: LucideMic,
  Minus: LucideMinus,
  Moon: LucideMoon,
  MoreHorizontal: LucideMoreHorizontal,
  Palette: LucidePalette,
  PanelRight: LucidePanelRight,
  Paperclip: LucidePaperclip,
  Pencil: LucidePencil,
  PenLine: LucidePenLine,
  PlugZap: LucidePlugZap,
  Plus: LucidePlus,
  Quote: LucideQuote,
  Radar: LucideRadar,
  Radio: LucideRadio,
  RadioTower: LucideRadioTower,
  ReceiptText: LucideReceiptText,
  RefreshCcw: LucideRefreshCcw,
  RefreshCw: LucideRefreshCw,
  Repeat2: LucideRepeat2,
  Rocket: LucideRocket,
  RotateCcw: LucideRotateCcw,
  Save: LucideSave,
  ScanLine: LucideScanLine,
  Search: LucideSearch,
  Send: LucideSend,
  Settings: LucideSettings,
  Share2: LucideShare2,
  Shield: LucideShield,
  ShieldAlert: LucideShieldAlert,
  ShieldCheck: LucideShieldCheck,
  SlidersHorizontal: LucideSlidersHorizontal,
  Smartphone: LucideSmartphone,
  Sparkles: LucideSparkles,
  Square: LucideSquare,
  Star: LucideStar,
  Store: LucideStore,
  Sun: LucideSun,
  Target: LucideTarget,
  ThumbsDown: LucideThumbsDown,
  ThumbsUp: LucideThumbsUp,
  TicketCheck: LucideTicketCheck,
  Trash2: LucideTrash2,
  TrendingUp: LucideTrendingUp,
  TriangleAlert: LucideTriangleAlert,
  Unlink: LucideUnlink,
  Upload: LucideUpload,
  User: LucideUser,
  UserPlus: LucideUserPlus,
  UserRound: LucideUserRound,
  Users: LucideUsers,
  UsersRound: LucideUsersRound,
  Wand2: LucideWand2,
  WandSparkles: LucideWandSparkles,
  Wrench: LucideWrench,
  X: LucideX,
  XCircle: LucideXCircle,
  Zap: LucideZap
} satisfies Record<string, LucideIcon>;
