import type { BlogPost } from "@/lib/blog-posts";
import { seoXiaohongshuCaseStudyPosts } from "@/lib/seo-xiaohongshu-case-study-posts";

const authorZh = "Finfold 编辑部";
const authorEn = "Finfold Editorial";
const accessedAt = "2026-08-24";

export const growthCaseStudyBlogPosts: BlogPost[] = [
  {
    slug: "reddit-shadowban-recovery-cases",
    publishedAt: "2026-08-19",
    updatedAt: "2026-08-24",
    platform: "Reddit",
    readingMinutes: 10,
    authorZh,
    authorEn,
    disclosureZh: "真人案例研究 · 公开用户名与经历来自原始 Reddit 帖子，身份未经独立核验。平台规则与申诉步骤以 Reddit 官方资料为准。",
    disclosureEn: "Real-case research · public handles and experiences come from original Reddit posts and identities are not independently verified. Platform rules and appeals follow official Reddit documentation.",
    titleZh: "三个 Reddit 账号申诉成功后，为什么帖子还是没有回来",
    titleEn: "Three Reddit Accounts Won Their Appeals. Their Posts Still Did Not Return",
    seoTitleZh: "Reddit Shadowban 申诉成功后帖子仍被删除怎么办｜真人案例",
    seoTitleEn: "Reddit Shadowban Recovery Cases and Missing Posts",
    descriptionZh: "三位公开账号都说申诉已经成功，旧帖子却仍显示被删除。把全站限制、CQS、Reputation Filter 和社区删除分开查，才知道下一步找谁。",
    descriptionEn: "Three public accounts said their appeals succeeded while old posts stayed removed. Their cases separate account restrictions, CQS, Reddit filters, and community moderation.",
    seoDescriptionZh: "结合三个 Reddit 公开账号的恢复经历与官方帮助文档，区分全站 shadowban、账号限制、CQS、Reputation Filter、AutoMod 和社区删除。",
    seoDescriptionEn: "Three firsthand Reddit recovery cases show how to distinguish a sitewide shadowban from CQS, Reputation Filter, AutoMod, spam filtering, and subreddit removals.",
    kickerZh: "增长案例 11 · 账号回来了，帖子没有",
    kickerEn: "GROWTH CASE 11 · THE ACCOUNT RETURNED, THE POSTS DID NOT",
    introZh: "Reddit 官方帮助页和三条恢复帖放在一起，会看到三个很像、又不完全相同的结果。Fresh-Night4118 说账号受限约一个月，恢复后 CQS 处在最低档。nuclearcowgirl 的旧帖需要管理员继续处理。Damariobros 的内容卡了两三个月，公开求助后才收到已经修复的回复。\n\n账号恢复只解决账号层面的限制。旧内容还可能留在过滤队列，或者继续受社区规则、AutoMod 和版主管理。低曝光也没有资格直接叫 shadowban。先确认限制发生在哪一层，才不会拿着一封申诉信到处敲错门。",
    introEn: "Reddit's current help pages and three public recovery threads show three similar outcomes with different details. Fresh-Night4118 reported a month-long restriction followed by a lowest-tier CQS. nuclearcowgirl needed an administrator to inspect old filtered posts. Damariobros reported content stuck for two to three months before a help thread ended with an administrator saying it was fixed.\n\nAn account appeal can restore the account without releasing every old submission from a separate filter. Subreddit rules, AutoMod, moderator actions, reputation controls, and sitewide restrictions are different systems. Low reach alone does not identify which one acted.",
    sectionsZh: [
      { heading: "Damariobros 等了两三个月，等来的先是一句账号已恢复", body: "Damariobros 在帮助社区写下的时间线很拧巴。申诉已经通过，账号能继续用，旧帖却还躺在 removed 状态里。他把症状和旧链接贴出来，社区成员检查后请管理员介入。页面最后留下管理员的回复，问题已经修复，当事人随后道谢。\n\n这段经历能证明旧帖后来得到处理，却不能替 Reddit 解释最初是谁删了内容。Damariobros 认为是 AutoMod，公开页面没有给出同样的归因。", pullQuote: "管理员修复了旧帖，最初原因仍没有公开结论。" },
      { heading: "Fresh-Night4118 拿回账号，CQS 还在最低档", body: "Fresh-Night4118 说限制持续了约一个月。申诉通过以后，他去查账号的 Contributor Quality Score，结果落在最低一档。帮助帖里的自动回复提醒，社区启用 Reputation Filter 时，新内容仍可能被拦。\n\n帖子没有给出信誉恢复用了几天，Reddit 也没有公开 CQS 的完整算法。把几天正常互动写成恢复承诺，会比原始材料多说一步。", pullQuote: "账号能用，不代表每个社区都会立刻放行新帖。" },
      { heading: "nuclearcowgirl 遇到的是同一种断层", body: "nuclearcowgirl 的账号已经解除限制，历史帖子仍显示被删除。帮助社区能做的事情很有限，只能先检查公开状态，再把问题交给管理员。三条记录放在一起，能看见一个共同症状。账号层面的申诉结束了，内容层面的过滤没有自动跟着结束。\n\n这也解释了为什么低浏览量不能直接叫 shadowban。单个社区的版主删除、AutoMod、Reputation Filter 和全站账号处置都可能留下相似的页面结果，处理入口却各不相同。", pullQuote: "removed 是页面结果，还不是原因。" },
      { heading: "普通账号先做一条干净测试，别急着换号", body: "先登录受影响账号查看 appeals 页面和收件箱。多个社区里的帖子、评论和个人主页同时异常，继续走账号申诉。只有一个社区出问题，先读规则，再把代表链接发给版主。旧帖在账号恢复后仍卡住，可以请求管理员核对过滤状态。\n\n测试只需要一条相关内容，不放链接，也不带产品名。发布后退出账号查看公开状态，同时保存通知和回复。新建账号绕过限制会制造新的违规风险，也会让原来的判断更难做。", pullQuote: "先找出是哪一层在处理内容，再决定找谁。" }
    ],
    sectionsEn: [
      { heading: "Damariobros waited two to three months and first received an account reinstatement", body: "The timeline in Damariobros's help thread is awkward. The appeal had succeeded and the account worked again, while old submissions still showed as removed. The account holder shared symptoms and links, community helpers inspected the public state, and an administrator was asked to intervene. The page ends with an administrator saying the issue was fixed and the account holder replying with thanks.\n\nThe thread supports the later restoration. It does not establish the original cause. Damariobros blamed AutoMod, but the public administrator reply did not confirm that explanation.", pullQuote: "The old posts were restored. The original cause remained unconfirmed." },
      { heading: "Fresh-Night4118 recovered the account while CQS remained at the lowest tier", body: "Fresh-Night4118 reported a restriction lasting about one month. After reinstatement, the account holder checked Contributor Quality Score and found the lowest tier. An automated help response warned that communities using Reputation Filter could still hold new submissions.\n\nThe thread gives no final recovery time, and Reddit does not publish the full CQS formula. Turning a few days of normal participation into a promise would go beyond the record.", pullQuote: "A usable account can still face a community reputation filter." },
      { heading: "nuclearcowgirl documented the same break between account and content", body: "nuclearcowgirl reported that the account restriction was reversed while historical submissions remained removed. The help community could inspect the public state and ask an administrator to review it. Together, the three records show one recurring symptom. The account appeal ended before every content filter cleared.\n\nThat is why low reach alone cannot diagnose a shadowban. Moderator removal, AutoMod, Reputation Filter, and sitewide account action can create similar visible outcomes while requiring different owners.", pullQuote: "Removed is a visible outcome, not yet a cause." },
      { heading: "Run one clean visibility check before creating another account", body: "Open the appeals page and inbox while logged into the affected account. When profiles, comments, and posts fail across communities, continue at the account layer. When the problem stays inside one subreddit, read its rules and send representative links to its moderators. Old posts stuck after reinstatement may need an administrator review.\n\nOne relevant post without a link or product name is enough for a visibility check. View it while logged out and save notices or replies. A replacement account can create ban-evasion risk and make the original diagnosis harder.", pullQuote: "Identify the layer first, then contact the person who can act." }
    ],
    experimentTitleZh: "用七天把限制层级查清楚",
    experimentTitleEn: "Use seven days to identify the layer that acted",
    experimentsZh: [
      { label: "01 / 留证据", body: "保存通知、申诉状态和三条代表链接，比较登录内外的可见差异。" },
      { label: "02 / 单变量测试", body: "选允许普通讨论的社区，只发一条无链接、无产品名的相关内容。" },
      { label: "03 / 找对处理人", body: "全站限制走申诉，单社区删除找版主，旧帖过滤请求管理员核对。" }
    ],
    experimentsEn: [
      { label: "01 / PRESERVE EVIDENCE", body: "Save notices, appeal state, and three representative links. Compare logged-in and logged-out visibility." },
      { label: "02 / RUN ONE CLEAN TEST", body: "Use one relevant, non-promotional post in a community that permits ordinary discussion." },
      { label: "03 / FIND THE OWNER", body: "Use appeals for sitewide action, moderators for subreddit action, and an admin review for stuck filters." }
    ],
    caseStudies: [
      { subjectName: "Fresh-Night4118", publicHandle: "Fresh-Night4118", timeframeZh: "公开帖称限制持续约一个月", timeframeEn: "Public post says the restriction lasted about one month", verificationZh: "公开账号自述", verificationEn: "Public-handle firsthand", goalZh: "账号恢复后避免再次被过滤", goalEn: "Avoid renewed filtering after reinstatement", actionsZh: ["持续使用原账号申诉", "确认账号已经恢复", "检查 CQS 并发现最低档", "询问恢复期怎样参与社区"], actionsEn: ["Appealed from the affected account", "Confirmed reinstatement", "Checked CQS and found the lowest tier", "Asked how to participate after recovery"], resultZh: "账号恢复，CQS 仍为最低，新内容可能继续触发社区信誉过滤", resultEn: "Account restored while CQS remained lowest and community reputation filters could still act", failureZh: "身份与最初限制原因未经独立核验，帖子没有给出最终恢复时间", failureEn: "Identity and original cause are unverified, and the thread gives no final recovery time", sourceUrl: "https://www.reddit.com/r/reddithelp/comments/1vn626a/my_shadow_ban_has_been_restored_what_now/" },
      { subjectName: "nuclearcowgirl", publicHandle: "nuclearcowgirl", timeframeZh: "账号恢复后约一个月内公开求助", timeframeEn: "Asked publicly within roughly a month of reinstatement", verificationZh: "公开账号自述", verificationEn: "Public-handle firsthand", goalZh: "恢复被过滤的旧帖", goalEn: "Restore old posts left in filters", actionsZh: ["说明误判已经解除", "公开旧帖仍被删除", "开放个人历史供检查", "由帮助社区请求管理员查看"], actionsEn: ["Reported a mistaken action had been reversed", "Documented old posts still removed", "Made history visible for inspection", "Had the community request an admin review"], resultZh: "帮助帖显示管理员介入路径被启动，参与者随后确认账号可以继续使用", resultEn: "The thread shows an administrator review path and participants later clearing the account to continue", failureZh: "公开页面无法证明每一条旧帖的最终状态", failureEn: "The public page does not verify the final state of every old post", sourceUrl: "https://www.reddit.com/r/reddithelp/comments/1uy6g7l/shadowbanned_and_posts_are_all_gone_can_they_be/" },
      { subjectName: "Damariobros", publicHandle: "Damariobros", timeframeZh: "称问题开始于两三个月前", timeframeEn: "Reported the problem began two to three months earlier", verificationZh: "公开账号自述", verificationEn: "Public-handle firsthand", goalZh: "恢复跨社区旧帖", goalEn: "Recover old posts across communities", actionsZh: ["完成账号申诉", "确认账号恢复但旧帖未恢复", "在帮助社区提供症状", "等待检查与管理员处理"], actionsEn: ["Completed an account appeal", "Confirmed reinstatement without old posts", "Documented the symptom", "Waited for inspection and administrator escalation"], resultZh: "管理员回复已修复，当事人随后致谢", resultEn: "An administrator replied that the issue was fixed and the account holder thanked the helpers", failureZh: "当事人对 AutoMod 的归因不能当成平台确认的原因", failureEn: "The account holder's attribution to AutoMod is not an official cause statement", sourceUrl: "https://www.reddit.com/r/reddithelp/comments/1uoguyr/need_help_restoring_posts_after_successful/" }
    ],
    sources: [
      { titleZh: "Reddit 账号状态总览", titleEn: "Reddit account status overview", url: "https://support.reddithelp.com/hc/en-us/articles/360045734591-Account-status-overview", kind: "official", publishedAt: "2026-03-29", accessedAt, supportsZh: "说明全站封禁、账号锁定与垃圾信息标记的区别。", supportsEn: "Distinguishes sitewide bans, security locks, and spam or inauthentic-activity flags." },
      { titleZh: "垃圾信息或非真实活动标记的申诉步骤", titleEn: "Appealing a spam or inauthentic-activity flag", url: "https://support.reddithelp.com/hc/en-us/articles/360045309012-My-account-was-flagged-for-spam-or-inauthentic-activity", kind: "official", publishedAt: "2025-08-14", accessedAt, supportsZh: "确认需要登录受影响账号并使用 appeals 页面。", supportsEn: "Confirms logging into the affected account and using the appeals page." },
      { titleZh: "Fresh-Night4118 的恢复经历", titleEn: "Fresh-Night4118 recovery thread", url: "https://www.reddit.com/r/reddithelp/comments/1vn626a/my_shadow_ban_has_been_restored_what_now/", kind: "public-handle-firsthand", accessedAt, supportsZh: "支撑约一个月申诉、账号恢复与最低 CQS 的自述。", supportsEn: "Supports the reported month-long restriction, reinstatement, and lowest CQS." },
      { titleZh: "nuclearcowgirl 的旧帖求助", titleEn: "nuclearcowgirl old-post thread", url: "https://www.reddit.com/r/reddithelp/comments/1uy6g7l/shadowbanned_and_posts_are_all_gone_can_they_be/", kind: "public-handle-firsthand", accessedAt, supportsZh: "支撑账号恢复后旧帖仍被过滤。", supportsEn: "Supports old posts remaining filtered after reinstatement." },
      { titleZh: "Damariobros 的旧帖修复记录", titleEn: "Damariobros restoration thread", url: "https://www.reddit.com/r/reddithelp/comments/1uoguyr/need_help_restoring_posts_after_successful/", kind: "public-handle-firsthand", accessedAt, supportsZh: "支撑两三个月时间线与管理员回复已修复。", supportsEn: "Supports the two-to-three-month timeline and administrator's fixed response." }
    ]
  },
  {
    slug: "reddit-growth-vote-manipulation-risk",
    publishedAt: "2026-08-19", updatedAt: "2026-08-24", platform: "Reddit", readingMinutes: 9, authorZh, authorEn,
    disclosureZh: "实名访谈与公开账号案例 · 流量、客户和收入数字均为当事人自报。协调投票、多账号和伪装提问只作为违规反例。",
    disclosureEn: "Named interview and public-handle cases · reach, customer, and revenue figures are self-reported. Coordinated voting, multiple accounts, and staged questions appear only as policy counterexamples.",
    titleZh: "Romain 在 Reddit 拿到 1100 万展示，也把最危险的做法说漏了嘴",
    titleEn: "Romain Reported 11 Million Reddit Impressions and Revealed the Riskiest Part of the Playbook",
    seoTitleZh: "Reddit 1100 万曝光案例｜互投和多账号为什么会被封",
    seoTitleEn: "11M Reddit Impressions and the Vote Manipulation Risk",
    descriptionZh: "镜头前，他举起笔记本展示收入，也讲出朋友互投、十五人点赞群和多账号。好故事值得拆，作弊那段得当场停下。",
    descriptionEn: "On camera, he held up the revenue dashboard and also described friend voting, a 15-person voting group, and multiple accounts. The story craft is useful; the manipulation is not.",
    seoDescriptionZh: "复盘 Romain 自报的 1100 万 Reddit 曝光、4 万访客和具体帖子转化，逐项解释协调投票、多账号与隐藏推广为什么可能触发封禁与社区处置。",
    seoDescriptionEn: "A critical review of Romain's self-reported 11M Reddit impressions and 40K visitors, separating useful storytelling from vote manipulation and account risk.",
    kickerZh: "增长案例 12 · 曝光很高，风险也写在访谈里", kickerEn: "GROWTH CASE 12 · THE RISK WAS INSIDE THE SUCCESS STORY",
    introZh: "Starter Story 的视频里，Romain 站在一排小说前面，把笔记本举到镜头中央。屏幕上的曲线很难看清，他报出的数字倒很清楚。Gojiberry AI 在几个月里拿到 1100 万次 Reddit 展示和 4 万多次网站访问，约前 100 位客户也从这里来。访谈里的月经常性收入出现过 2.4 万美元和约 3 万美元两种说法，片头后来写成 3.4 万美元。它们都是当事人自报，没有独立审计。\n\n把整段访谈和 Reddit 现行规则逐项对照，最有用的材料出现在一笔 1250 美元的失败投放里。风险也由 Romain 自己讲了出来。他找朋友集中点赞评论，加入十五人的营销互投群，还用不同浏览器管理多个账号。一条访谈把好故事怎么写、分发又怎样越过红线，放在了同一段经历里。",
    introEn: "In the Starter Story video, Romain stands in front of a wall of novels and holds a laptop toward the camera. The chart is hard to read, but his claims are clear. Gojiberry AI reportedly received 11 million Reddit impressions and more than 40,000 site visits in a few months, with roughly the first 100 customers attributed to the channel. The interview shows both $24K and roughly $30K MRR, while the later video title says $34K. These are founder-reported figures, not an independent audit.\n\nThis review compares the interview with Reddit's current rules. The most useful material begins with a failed $1,250 influencer campaign. The most dangerous material also comes from Romain himself. He describes concentrated votes from friends, a 15-person marketer voting group, and multiple browser accounts. One interview contains both the craft of a strong case story and the distribution behavior that crosses the line.",
    sectionsZh: [
      { heading: "那条火起来的帖子，起点是一张 1250 美元的账单", body: "Romain 找了五位 LinkedIn 影响者替产品做推广，一共花了 1250 美元。结果没有按计划来。他把预算、过程、截图和意外结果整理成 Reddit 帖子，标题里直接交代自己花了多少钱。帖子据他自报拿到 16 万浏览和 543 个赞，约 2000 人随后访问网站，估计带来 10 到 15 位客户。\n\n这段经验很朴素。读者愿意看，是因为钱已经花了，结果也真的砸在团队身上。故事里有一次决定，有账单，还有不太好看的后果。把产品名拿走，它仍然值得读。", pullQuote: "" },
      { heading: "他先口述，AI 只负责把材料收拾整齐", body: "Romain 说自己会先找一件有冲突的真事，再把经历口述出来，让 AI 帮忙整理。截图和数字随后补进去，他本人留在评论区继续回答。这个顺序值得保留。原始经历先出现，工具在后面做编辑工作。\n\n1100 万展示听起来很大，换成业务账就得慢下来。展示不等于访问，访问也不等于付费。访谈没有提供一份可核验的完整归因报表。对普通创始人更现实的预期，是先拿一件发生过的事换来几次认真讨论，再看有没有人愿意点进产品。", pullQuote: "" },
      { heading: "十五人的互投群一出现，这套方法就过界了", body: "访谈继续往下，Romain 提到朋友会在帖子发出后集中点赞评论。他还加入了十五人的营销群，成员之间替帖子投票。不同账号放在不同浏览器里，活动记录也尽量藏起来。\n\nReddit 的规则写得很直。组织一群人给指定内容投票，用多个账号改变票数，都属于操纵。这里没有可以模糊解释的空间。第一波互动就算真的把帖子推了上去，也会同时留下违规证据。", pullQuote: "" },
      { heading: "能带走的只有故事、证据和正常回复", body: "如果要复做这个案例，我会保留那张账单，保留失败过程，也保留作者在评论区回答质疑。账号只用一个，身份照实说明。社区不允许推广时，产品链接就不放。\n\n七天足够跑一次小测试。选一笔真实投入，把时间线和截图收齐，写清结果到哪里为止。发布后分别看展示、访问和有效对话。只有展示，没有人继续问，也没有人访问，说明选题还不够好。帖子被删或收到警告，当天就停。", pullQuote: "" }
    ],
    sectionsEn: [
      { heading: "The post began with a $1,250 bill", body: "Romain paid five LinkedIn influencers a total of $1,250 to promote the product. The outcome disappointed him. He turned the budget, process, screenshots, and surprise into a Reddit post that stated the cost in the title. He reports 160,000 views, 543 upvotes, about 2,000 site visits, and an estimated 10 to 15 customers.\n\nThe story had a decision, a bill, and an outcome the team had to live with. Remove the product name and it still gives a reader something useful.", pullQuote: "" },
      { heading: "He dictates the experience before AI edits it", body: "Romain says he finds a true event with tension, dictates the experience, and then uses AI to organize it. Screenshots and numbers arrive afterward, and he stays in the comments to answer questions. The lived material comes first. The tool performs editorial work later.\n\nEleven million impressions still need to be slowed down. Impressions are not visits, and visits are not paid customers. A more realistic expectation for an ordinary founder is a few serious conversations from one well-documented event, followed by evidence of whether anyone visits the product.", pullQuote: "" },
      { heading: "The 15-person voting group crosses the line", body: "Later in the interview, Romain describes friends voting and commenting immediately after publication. He also mentions a 15-person marketer group whose members voted for one another, with separate accounts kept in separate browsers.\n\nReddit's rule is direct. Coordinating votes on selected content and using multiple accounts to alter vote counts are manipulation. Early momentum produced this way can become evidence of the violation itself.", pullQuote: "" },
      { heading: "Keep the story, proof, and ordinary replies", body: "A defensible version keeps the bill, the failed sequence, and the founder answering criticism. It uses one stable identity and an honest disclosure. If the community does not permit promotion, the product link stays out.\n\nSeven days is enough for a small test. Gather one real expense, timeline, and screenshot. Track impressions, visits, and qualified conversations separately. Stop on a removal or warning. If reach produces no questions or visits, change the subject instead of manufacturing the first wave.", pullQuote: "" }
    ],
    experimentTitleZh: "把高曝光案例改造成合规证据帖", experimentTitleEn: "Turn a high-reach story into a policy-safe evidence post",
    experimentsZh: [{ label: "01 / 摊开一笔账", body: "公开预算、步骤、截图和结果边界。" }, { label: "02 / 删掉假启动", body: "不互投、不代问、不多账号。" }, { label: "03 / 分层记结果", body: "分别记录展示、访问、有效对话与付费。" }],
    experimentsEn: [{ label: "01 / OPEN THE LEDGER", body: "Publish budget, sequence, proof, and limits." }, { label: "02 / REMOVE THE FAKE START", body: "Use no vote ring, staged question, or account rotation." }, { label: "03 / SEPARATE OUTCOMES", body: "Track reach, visits, qualified conversations, and paid customers." }],
    caseStudies: [
      { subjectName: "Romain", product: "Gojiberry AI", timeframeZh: "访谈称约四个月内从零增长", timeframeEn: "Interview says growth from zero over roughly four months", verificationZh: "实名第一手访谈", verificationEn: "Named firsthand interview", goalZh: "用 Reddit 获得早期客户", goalEn: "Use Reddit for early customers", actionsZh: ["寻找带成本的故事", "口述后用 AI 整理", "加入截图和数字", "逐条回复评论"], actionsEn: ["Found stories with costs", "Dictated and organized drafts with AI", "Added screenshots and metrics", "Replied to comments"], resultZh: "自报 1100 万展示、4 万访客、约前 100 位客户和约 3 万 MRR", resultEn: "Self-reported 11M impressions, 40K visitors, roughly 100 early customers, and about 30K MRR", failureZh: "同时披露协调投票、多账号与隐藏推广痕迹", failureEn: "Also disclosed coordinated voting, multiple accounts, and concealed promotion", sourceUrl: "https://www.starterstory.com/roman" },
      { subjectName: "thankjupiter", publicHandle: "thankjupiter", product: "Popsy AI", timeframeZh: "2025 年公开帖", timeframeEn: "Public post from 2025", verificationZh: "公开账号自述", verificationEn: "Public-handle firsthand", goalZh: "提炼 Reddit 推广结构", goalEn: "Extract Reddit promotion patterns", actionsZh: ["分析产品数据", "归纳三类帖子", "列出互动样本", "建议产品出现位置"], actionsEn: ["Analyzed product data", "Grouped three post types", "Listed engagement examples", "Suggested product placement"], resultZh: "形成三类方法，数据规模为公司自报", resultEn: "Published three methods with company-reported dataset scale", failureZh: "建议朋友代问链接并把封号当成本", failureEn: "Suggested a staged friend question and treated bans as a cost", sourceUrl: "https://www.reddit.com/r/SaaS/comments/1lq13x4/3_ways_to_promote_your_product_on_reddit_without/" }
    ],
    sources: [
      { titleZh: "Romain 的 Reddit 增长访谈", titleEn: "Romain's Reddit growth interview", url: "https://www.starterstory.com/roman", kind: "named-firsthand", accessedAt, supportsZh: "支撑自报数字、帖子数据、内容流程与协调投票披露。", supportsEn: "Supports self-reported figures, post metrics, content process, and coordinated-voting disclosure." },
      { titleZh: "Reddit 关于操纵投票的规则", titleEn: "Reddit policy on vote manipulation", url: "https://support.reddithelp.com/hc/en-us/articles/360043066412-Disrupting-Communities", kind: "official", publishedAt: "2026-05-19", accessedAt, supportsZh: "明确禁止协调投票、多账号操纵和规避封禁。", supportsEn: "Explicitly prohibits coordinated voting, multi-account manipulation, and ban evasion." },
      { titleZh: "Popsy AI 的公开复盘", titleEn: "Popsy AI public breakdown", url: "https://www.reddit.com/r/SaaS/comments/1lq13x4/3_ways_to_promote_your_product_on_reddit_without/", kind: "company-reported", accessedAt, supportsZh: "支撑自报数据规模、帖子分类和朋友代问建议。", supportsEn: "Supports the reported dataset scale, post categories, and staged-friend suggestion." }
    ]
  },
  {
    slug: "reddit-first-customers-manual-outreach", publishedAt: "2026-08-19", updatedAt: "2026-08-30", platform: "Reddit", readingMinutes: 9, authorZh, authorEn,
    disclosureZh: "公开账号与实名访谈案例 · firsteyes AI 原帖正文在 2026 年 8 月 24 日复核时已经删除，40 位付费用户仍按未审计的当事人自报处理。",
    disclosureEn: "Public-handle and named interview cases · the firsteyes AI post body was deleted when rechecked on August 24, 2026. The 40 paying users remain an unaudited firsthand claim.",
    titleZh: "firsteyes 的 40 位付费用户帖删了正文，评论区还剩下什么", titleEn: "The FirstEyes AI 40-Customer Reddit Post Was Deleted. What Can Still Be Verified?",
    seoTitleZh: "Reddit 手工获客复盘｜firsteyes 删除正文后还能核验什么", seoTitleEn: "FirstEyes AI Reddit Case: What Can Still Be Verified | Finfold",
    descriptionZh: "标题和评论区还在，正文已经删除。40 位付费用户只能算原帖标题中的自报，Paperflite 两年的论坛记录提供了另一条可查路径。",
    descriptionEn: "The FirstEyes AI post still shows its 40-customer claim and comments, while the body is gone. We separate the surviving evidence from what cannot be verified.",
    seoDescriptionZh: "拆解 firsteyes AI 和 Paperflite 的真人获客步骤，包括找问题帖、手工私信、论坛回答、LinkedIn 跟进、结果口径和停止条件。",
    seoDescriptionEn: "FirstEyes AI claimed 40+ paying customers from manual Reddit outreach. We separate the deleted post claim from what its comments and cited sources still verify.",
    kickerZh: "增长案例 13 · 一个个找人，比群发慢得多", kickerEn: "GROWTH CASE 13 · ONE PERSON AT A TIME",
    introZh: "firsteyes AI 那条 Reddit 地址现在还能打开。标题仍写着跨过 40 位付费用户，发帖人和正文都显示 deleted，评论区却留了下来。原账号 Illustrious_Cake0018 在回复里说，自己会私信已经写出相关问题的人，效果较好的社区包括 micro_saas、saasbuild、SaaS 和 buildinpublic，所有联系都由他手工完成。\n\n标题保住了 40 多位付费用户这句自报，删掉的正文带走了时间线和更多上下文。评论能核对手工私信这件事，不能证明客户数量。Paperflite 的材料完整得多。SaaS Club 根据联合创始人 Yega Kumarappan 的访谈整理，团队从 2018 年起花了约两年待在 Quora 和 Reddit，先回答问题，合适时提产品，再去 LinkedIn 继续聊。",
    introEn: "The firsteyes AI Reddit URL still opens. Its title continues to claim more than 40 paying customers, while the original poster and body both show as deleted. The comment thread remains. In replies, Illustrious_Cake0018 says the outreach targeted people who had already described a relevant problem, names micro_saas, saasbuild, SaaS, and buildinpublic as the strongest communities, and says every contact was handled manually.\n\nThe title preserves the 40-customer claim, while the deleted body removed its timeline and wider context. The comments support the manual outreach, not the customer count. The Paperflite record is more complete. A SaaS Club playbook based on an interview with cofounder Yega Kumarappan says the team spent about two years answering questions on Quora and Reddit, mentioning the product when relevant, and continuing conversations on LinkedIn.",
    sectionsZh: [
      { heading: "删掉的正文不能继续替数字作证", body: "公开页面仍能核对几件事。标题自称有 40 多位付费用户，Illustrious_Cake0018 在评论里说私信对象已经写过产品能解决的问题，也点名了几个效果较好的社区。他后来回答另一位提问者，私信没有自动化。\n\n页面没有留下客户名单、付款记录和归因过程。评论能说明发帖账号怎样描述方法，不能把标题里的业绩变成已经审计的结果。", pullQuote: "评论保住了方法的一角，没有替客户数字补回证据。" },
      { heading: "评论区没有跟着消失，质疑也留了下来", body: "有人质疑网站几乎没有流量，也有人说自己在 Reddit 上完全没得到结果。发帖账号回应，渠道效果取决于产品类别。评论无法证明 40 位付费用户为真或为假，它至少保住了一件重要的事。这个数字从一开始就有人追问。\n\n所以 40 位付费用户只能写成当事人自报。普通团队也不该拿它当七天实验的预期。", pullQuote: "一项业绩有人质疑，文章就该把质疑和数字放在一起。" },
      { heading: "Paperflite 留下了一条还能查的慢路", body: "SaaS Club 的整理来自联合创始人 Yega Kumarappan 的访谈。团队从 2018 年起在 Quora 和 Reddit 回答销售内容、分发和知识管理问题，合适时提到 Paperflite，再去 LinkedIn 接着聊。这件事做了约两年。\n\n来源也写得很克制。论坛带来一小批质量较高的机会，首位付费客户来自其他入口。它说明公开回答可以为后续对话铺路，没有证明论坛能稳定带来某个转化率。", pullQuote: "两年的投入，只能换来一条值得继续做的渠道线索。" },
      { heading: "想试手工联系，七个人已经够看出问题", body: "先保存十条和产品直接相关的公开问题，挑七位最匹配的人。每条消息只引用一个原帖细节，先问是否愿意了解，不放链接，也不批量复制。对方答应以后再说明产品和自己的关系。\n\n记录有效回复、同意试用、完成试用和付费。连续七人无人回复，回头检查目标和开场；两人觉得被打扰，立即停下。收到社区警告也要停。这个实验能告诉你对话是否成立，不能许诺 40 位客户。", pullQuote: "七条人工消息足够查问题匹配，还不够预测收入。" }
    ],
    sectionsEn: [
      { heading: "A deleted body can no longer support the number", body: "The public page still supports a few points. Its title claims more than 40 paying customers. In comments, Illustrious_Cake0018 says the outreach targeted people who had already written about a relevant problem, names the communities that worked best, and says the DMs were not automated.\n\nThe page does not provide a customer list, payment record, or attribution trail. The comments support how the account described the method. They do not turn the headline result into an audited figure.", pullQuote: "The comments preserve part of the method, not proof of the customer count." },
      { heading: "The comments survived, including the objections", body: "One person questioned the site's apparent traffic and another said Reddit had produced no result for their product. The posting account replied that channel fit depended on the category. The comments cannot prove or disprove 40 paying customers. They preserve one important fact. People challenged the number from the start.\n\nThe 40-customer figure must remain an account claim. It is not a normal seven-day expectation for another team.", pullQuote: "When a result was challenged, the challenge belongs beside the number." },
      { heading: "Paperflite left a slower record that readers can still inspect", body: "The SaaS Club account is based on an interview with cofounder Yega Kumarappan. Starting in 2018, the team answered questions about sales content, distribution, and knowledge management on Quora and Reddit, mentioned Paperflite when relevant, and continued conversations on LinkedIn. The work lasted about two years.\n\nThe source stays cautious. Forums produced a small set of qualified opportunities, while the first paying customer came through another route. The case supports forum answers as a beginning for later conversations, not a stable conversion rate.", pullQuote: "Two years of work produced a channel worth continuing, not a guaranteed yield." },
      { heading: "Seven manual contacts are enough to expose a targeting problem", body: "Save ten public questions that directly match the product and choose the seven strongest people. Reference one source detail in each message, ask permission before explaining, and do not lead with a link. Disclose the product relationship once the person agrees to continue.\n\nTrack substantive replies, trial consent, completed use, and payment. Recheck targeting after seven non-responses. Stop after two people call the message intrusive or after any community warning. This experiment can test whether a conversation starts. It cannot promise 40 customers.", pullQuote: "Seven messages can test problem fit. They cannot forecast revenue." }
    ],
    experimentTitleZh: "用七条人工私信验证问题匹配", experimentTitleEn: "Validate problem fit with seven manual messages",
    experimentsZh: [{ label: "01 / 找十个问题", body: "只保存明确描述产品可解决麻烦的原帖。" }, { label: "02 / 手工联系七人", body: "每条引用一个原帖细节，先问是否愿意了解。" }, { label: "03 / 记录真实结果", body: "分别记录回复、试用、完成和付费。" }],
    experimentsEn: [{ label: "01 / FIND TEN PROBLEMS", body: "Save only posts that describe a problem the product can actually address." }, { label: "02 / CONTACT SEVEN", body: "Reference one source detail and ask permission before explaining the product." }, { label: "03 / RECORD OUTCOMES", body: "Separate replies, trials, completed use, and payment." }],
    caseStudies: [
      { subjectName: "Illustrious_Cake0018", publicHandle: "Illustrious_Cake0018", product: "firsteyes AI", timeframeZh: "2026 年 8 月公开帖", timeframeEn: "Public post from August 2026", verificationZh: "公开账号自述", verificationEn: "Public-handle firsthand", goalZh: "找到前一批付费用户", goalEn: "Find an early group of paying users", actionsZh: ["找问题帖", "私信相关用户", "点名有效社区", "手工跟进"], actionsEn: ["Found problem posts", "Messaged relevant users", "Named the strongest communities", "Followed up manually"], resultZh: "标题自报超过 40 位付费用户", resultEn: "The title self-reports more than 40 paying customers", failureZh: "正文已删除，评论区质疑网站流量，客户数字未经独立审计", failureEn: "The body is deleted, commenters questioned site traffic, and the customer figure is not independently audited", sourceUrl: "https://www.reddit.com/r/saasbuild/comments/1vnirnl/crossed_40_paying_customers_with_my_saas_heres/" },
      { subjectName: "Yega Kumarappan", product: "Paperflite", timeframeZh: "2018 年启动后约两年", timeframeEn: "Roughly two years after a 2018 launch", verificationZh: "实名访谈的二手整理", verificationEn: "Secondary summary of named interview", goalZh: "从高意向问题建立早期销售机会", goalEn: "Build early pipeline from high-intent questions", actionsZh: ["回答论坛问题", "相关时提产品", "转到 LinkedIn 私信", "快速回应站内咨询"], actionsEn: ["Answered forum questions", "Mentioned the product when relevant", "Followed up on LinkedIn", "Responded quickly to inbound chat"], resultZh: "案例称小范围高质量线索带来首批客户，首位付费客户来自其他入口", resultEn: "Case says a small pool of qualified leads produced early customers, while the first payer did not convert directly from a forum", failureZh: "来源是基于播客的二手 playbook，论坛的直接转化无法单独确认", failureEn: "Source is a secondary playbook based on a podcast and direct forum attribution cannot be isolated", sourceUrl: "https://saasclub.io/playbooks/yega-kumarappan-quora-reddit-first-customers-story/" }
    ],
    sources: [
      { titleZh: "firsteyes AI 公开复盘页面", titleEn: "firsteyes AI public retrospective page", url: "https://www.reddit.com/r/saasbuild/comments/1vnirnl/crossed_40_paying_customers_with_my_saas_heres/", kind: "public-handle-firsthand", accessedAt, supportsZh: "标题保留 40 多位付费用户自报，评论保留相关问题私信、有效社区和手工执行说法；正文已经删除。", supportsEn: "The title preserves the 40-customer claim and comments preserve statements about problem-led DMs, useful communities, and manual execution; the body is deleted." },
      { titleZh: "Paperflite 前期论坛获客整理", titleEn: "Paperflite early forum acquisition playbook", url: "https://saasclub.io/playbooks/yega-kumarappan-quora-reddit-first-customers-story/", kind: "secondary-analysis", accessedAt, supportsZh: "支撑两年论坛投入、三步动作与首位客户来源。", supportsEn: "Supports the two-year forum effort, three-step motion, and first-customer source." },
      { titleZh: "Reddit 垃圾信息规则", titleEn: "Reddit spam policy", url: "https://support.reddithelp.com/hc/en-us/articles/360043504051-Spam", kind: "official", publishedAt: "2026-05-19", accessedAt, supportsZh: "明确限制大量未经请求的私信和重复推广。", supportsEn: "Restricts large unsolicited messaging and repetitive promotion." }
    ]
  },
  {
    slug: "reddit-post-patterns-popsy-ai", publishedAt: "2026-08-19", updatedAt: "2026-08-24", platform: "Reddit", readingMinutes: 9, authorZh, authorEn,
    disclosureZh: "公司自报数据与公开帖子样本 · Popsy AI 的数据规模和分类来自其公开账号，互动数是抓取时页面记录，不代表产品转化。",
    disclosureEn: "Company-reported data and public post samples · Popsy AI's dataset scale and categories come from its public account. Engagement figures are page snapshots, not product conversions.",
    titleZh: "Popsy AI 说自己每天拆数十万 Reddit 帖子，哪些经验还能用", titleEn: "Popsy AI Says It Analyzes Hundreds of Thousands of Reddit Posts a Day. Which Lessons Hold Up?",
    seoTitleZh: "Popsy AI Reddit 帖子分析｜公司自报样本与合规边界", seoTitleEn: "Popsy AI Reddit Post Analysis with Source and Policy Limits",
    descriptionZh: "两条公司账号帖子给出故事、教程和免费帮助的样本，也夹着朋友代问链接的建议。内容结构可以查，样本规模和暗招要分开判断。",
    descriptionEn: "Stories, deep tutorials, and bounded free help can earn discussion. Staged questions and concealed promotion turn content lessons into platform risk.",
    seoDescriptionZh: "用 Popsy AI 的公开帖子样本逐项拆解 Reddit 标题、数字证据、深度教程和免费帮助结构，并对照官方规则排除朋友代问、隐藏推广与重复发布。",
    seoDescriptionEn: "A case-led breakdown of Reddit story, tutorial, and free-help formats from Popsy AI, with official policy checks against staged questions and hidden promotion.",
    kickerZh: "增长案例 14 · 样本能看，暗招要删", kickerEn: "GROWTH CASE 14 · KEEP THE PATTERNS, DROP THE TRICKS",
    introZh: "公开账号 thankjupiter 发过两份 Popsy AI 的分析。一份声称产品每天处理数十万条 Reddit 帖子，把 r/SaaS 的高互动内容分成故事、深度教程和免费帮助。另一份写着分析了 1 万条头部帖子，又列出带数字的成功经历、失败复盘、行业争议、教程和免费资源。两组样本量都来自公司账号自报。\n\n帖子里有些经验很实在。标题写出时间、代价和结果，正文交代读者能核对的证据。风险藏在同一份建议里。它让朋友在评论区代问产品链接，安排好的商业互动便会装成自然兴趣。结构可以学，这个动作不能跟。",
    introEn: "The public account thankjupiter published two Popsy AI analyses. One claims the product processes hundreds of thousands of Reddit posts each day and groups high-engagement r/SaaS content into stories, deep teaching, and free help. The other says it analyzed 10,000 top posts and lists metric-led wins, failures, debates, tutorials, and resources. Both sample sizes are company-reported.\n\nSome advice is concrete. Put time, cost, and outcome in the title, then keep evidence close enough for readers to inspect. The risk appears in the same playbook. It suggests asking a friend to request the product link, making an arranged commercial interaction look like organic interest. The structure is useful. The staged question is not.",
    sectionsZh: [
      { heading: "一万条帖子先教会人把数字说完整", body: "Popsy 的第二份帖子列出一批带数字的标题，里面有月经常性收入、用户数和退出金额。它同时承认，大数字没有证据会招来质疑。对创业者来说，能拿走的经验是把时间口径和截图放回数字旁边。\n\n写 1 万美元 MRR，就要交代这是哪个月、毛收入还是经常性收入。写第一位付费用户，也要讲清用了多久，尝试过什么，哪里没有奏效。", pullQuote: "数字写得越大，口径越该离它近。" },
      { heading: "故事和教程好用，因为读者拿走以后还能做事", body: "两份分析都偏爱已经发生的变化。辞职、第一位客户、融资失败，这些故事自带时间和后果。教程则要写出样本怎么选、步骤怎么走。读者不点产品链接，也能照着完成一个小动作。\n\n免费帮助也有同样的要求。说清审查什么、只接几个人、什么时候回复。承诺五个名额，就真的把五份做完。", pullQuote: "拿走产品名，正文仍然能帮到人。" },
      { heading: "让朋友代问链接，把一条好建议弄坏了", body: "Popsy 的推广帖建议，评论区没人问产品时，可以找朋友来问。这个动作的问题很具体。读者看到的是自然好奇，背后却是一场提前安排的商业互动。社区无法判断兴趣从哪里来，帖子里的其他建议也跟着变得可疑。\n\n公开身份、说明产品关系，互动数可能少一点。换来的东西更有用。每条评论都来自读者自己的判断，团队才能知道故事究竟有没有打中人。", pullQuote: "安排出来的好奇心，不能拿来验证内容。" },
      { heading: "七天只试三篇，结果要分开记", body: "第一篇写一个真实里程碑，把时间、代价和结果放进去。第二篇拿团队做过的一项工作写教程，给出可照做的步骤。第三篇提供五个名额的小审查，先写清交付范围。每篇只去一个规则允许的社区，产品关系直接披露。\n\n复盘时把有内容的评论、资料页访问、试用和咨询分开记录。互动多却没人继续了解，受众可能不匹配。版主提醒出现就停，不换账号重发。", pullQuote: "三篇透明的小样本，够判断哪种内容值得继续。" }
    ],
    sectionsEn: [
      { heading: "The 10,000-post analysis is most useful when it makes a number complete", body: "Popsy's second post lists metric-led titles involving monthly recurring revenue, user counts, and exit values. It also acknowledges that large numbers without proof attract skepticism. The useful lesson is to keep the time definition and evidence beside the claim.\n\nA $10K MRR headline needs the month and the revenue definition. A first-customer story needs the elapsed time, the attempts, and what failed.", pullQuote: "The larger the number, the closer its definition should be." },
      { heading: "Stories and tutorials work when the reader can act without the product", body: "Both Popsy analyses favor completed changes. Quitting a job, finding a first customer, and losing raised capital already contain time and consequence. A tutorial has to disclose how the sample was selected and how the steps work. The reader should finish one small action without clicking a product link.\n\nFree help has the same obligation. State the review, capacity, and response time. If the post offers five places, complete all five.", pullQuote: "Remove the product name and the body should still help." },
      { heading: "A staged friend question damages an otherwise useful post", body: "Popsy's promotion post suggests asking a friend to request the product when nobody else does. Readers see organic curiosity while the commercial interaction was arranged in advance. The community loses the ability to judge where the interest came from, and the rest of the advice becomes harder to trust.\n\nDisclosure may reduce visible engagement. It produces a cleaner signal because each comment comes from the reader's own judgment.", pullQuote: "Arranged curiosity cannot validate the content." },
      { heading: "Publish three disclosed tests and keep the outcomes separate", body: "Use a real milestone for the first post, including time, cost, and result. Turn completed work into a runnable tutorial for the second. Offer five places for a small review in the third and state the deliverable. Send each post to one community that permits it and disclose the product relationship.\n\nTrack substantive comments, profile visits, trials, and inquiries separately. High engagement without further interest can reveal an audience mismatch. Stop after a moderator warning instead of reposting from another account.", pullQuote: "Three transparent samples are enough to choose what deserves another week." }
    ],
    experimentTitleZh: "用三篇透明帖子验证三种结构", experimentTitleEn: "Validate three structures with three disclosed posts",
    experimentsZh: [{ label: "01 / 真实故事", body: "写一个有时间、选择、代价和结果的里程碑。" }, { label: "02 / 可执行教程", body: "交出样本、筛选和步骤。" }, { label: "03 / 有限帮助", body: "限定五人、范围和回复时间。" }],
    experimentsEn: [{ label: "01 / REAL STORY", body: "Use a milestone with time, choice, cost, and outcome." }, { label: "02 / RUNNABLE TUTORIAL", body: "Give the sample, selection method, and steps." }, { label: "03 / BOUNDED HELP", body: "Cap the offer at five people with a clear response time." }],
    caseStudies: [
      { subjectName: "thankjupiter", publicHandle: "thankjupiter", product: "Popsy AI", timeframeZh: "两条 2025 年公开分析帖", timeframeEn: "Two public analysis posts from 2025", verificationZh: "公司自报", verificationEn: "Company-reported", goalZh: "找出 r/SaaS 高互动结构", goalEn: "Identify high-engagement r/SaaS structures", actionsZh: ["分析大量帖子", "按结构分组", "列互动样本", "总结产品出现方式"], actionsEn: ["Analyzed a large corpus", "Grouped post structures", "Listed engagement examples", "Summarized product placement"], resultZh: "自报每天分析数十万帖子，并另称分析 1 万条头部帖", resultEn: "Reported analyzing hundreds of thousands daily and a separate 10K top-post sample", failureZh: "朋友代问和隐藏推广建议违背真实参与", failureEn: "Staged friend questions and concealed promotion undermine authentic participation", sourceUrl: "https://www.reddit.com/r/SaaS/comments/1lq13x4/3_ways_to_promote_your_product_on_reddit_without/" },
      { subjectName: "Capital-Bank8815", publicHandle: "Capital-Bank8815", timeframeZh: "回顾 2015 年至项目资金耗尽", timeframeEn: "Retrospective covering a 2015 raise through the end of runway", verificationZh: "公开账号自述", verificationEn: "Public-handle firsthand", goalZh: "复盘 250 万美元融资后的失败", goalEn: "Explain a failure after a reported $2.5M raise", actionsZh: ["公布融资背景", "列平台受众数据", "公开获客成本", "说明一次佣金收入"], actionsEn: ["Published funding context", "Listed platform audience metrics", "Reported acquisition cost", "Explained one affiliate-revenue event"], resultZh: "自报微信数十万关注、单文 200 万阅读和一天 1.5 万美元佣金，项目最终停止", resultEn: "Reported hundreds of thousands of WeChat followers, a 2M-read article, and $15K affiliate commissions in one day before shutdown", failureZh: "账号身份和数字未经独立核验，作者也说明英文带 AI 翻译痕迹", failureEn: "Identity and figures are unverified, and the author notes AI-assisted translation", sourceUrl: "https://www.reddit.com/r/SaaS/comments/1ljtkzt/i_raised_25m_ten_years_ago_heres_what_i_learned/" }
    ],
    sources: [
      { titleZh: "Popsy AI 三类推广结构", titleEn: "Popsy AI on three promotion structures", url: "https://www.reddit.com/r/SaaS/comments/1lq13x4/3_ways_to_promote_your_product_on_reddit_without/", kind: "company-reported", accessedAt, supportsZh: "支撑三类结构、样本互动与朋友代问建议。", supportsEn: "Supports the three formats, engagement examples, and staged-friend suggestion." },
      { titleZh: "Popsy AI 的 1 万帖分析", titleEn: "Popsy AI analysis of 10K top posts", url: "https://www.reddit.com/r/SaaS/comments/1ljh5ia/i_analyzed_10k_top_posts_on_rsaas_5_post_types/", kind: "company-reported", accessedAt, supportsZh: "支撑五类帖子、数字标题和证据建议。", supportsEn: "Supports five post types, metric-led headlines, and proof guidance." },
      { titleZh: "融资失败公开复盘样本", titleEn: "Public retrospective on a failed funded startup", url: "https://www.reddit.com/r/SaaS/comments/1ljtkzt/i_raised_25m_ten_years_ago_heres_what_i_learned/", kind: "public-handle-firsthand", accessedAt, supportsZh: "提供失败故事的时间、成本、平台数据和结果样本。", supportsEn: "Provides a failure-story sample with time, cost, platform metrics, and outcome." },
      { titleZh: "Reddit 垃圾信息规则", titleEn: "Reddit spam policy", url: "https://support.reddithelp.com/hc/en-us/articles/360043504051-Spam", kind: "official", publishedAt: "2026-05-19", accessedAt, supportsZh: "规定真实参与与重复推广边界。", supportsEn: "Defines authentic participation and repetitive-promotion boundaries." }
    ]
  },
  {
    slug: "validate-demand-before-building", publishedAt: "2026-08-19", updatedAt: "2026-08-24", platform: "SEO + Reddit", readingMinutes: 9, authorZh, authorEn,
    disclosureZh: "公开拆解与第一人称复盘 · voiceisolator 页面数据来自哥飞公开帖子，Felix 的用户与收入数据为本人自报，评论区质疑一并保留。",
    disclosureEn: "Public teardown and firsthand retrospective · voiceisolator page observations come from Ge Fei's public post. Felix's user and revenue figures are self-reported and challenges remain visible.",
    titleZh: "Felix 用 8 到 10 份回答找到第一批用户，哥飞把问题接到了搜索页上", titleEn: "Felix Found His First Users in 8 to 10 Survey Replies. Ge Fei Carried the Question into Search",
    seoTitleZh: "需求验证真人案例｜哥飞 SEO 拆解与 Reddit 前 100 用户", seoTitleEn: "Demand Validation Cases from SEO and Reddit Research",
    descriptionZh: "Felix 先在 Reddit 和陌生人交换反馈，两周后自报有了 100 个用户。哥飞沿着用户会搜的那句话，拆开一个 1755 词的工具页。",
    descriptionEn: "Felix exchanged project feedback with strangers on Reddit and later reported 100 users in two weeks. Ge Fei followed the user's query through a 1,755-word tool page.",
    seoDescriptionZh: "两个真人增长案例还原需求到页面的具体步骤，包括关键词、canonical、H2、FAQ、Reddit 调研、反馈交换和两周前 100 用户。",
    seoDescriptionEn: "Two concrete growth cases connect demand research to titles, canonical, H2s, FAQs, Reddit surveys, feedback exchange, and a self-reported first 100 users.",
    kickerZh: "增长案例 15 · 先找需求，再把页面写明白", kickerEn: "GROWTH CASE 15 · FIND DEMAND, THEN EXPLAIN THE PAGE",
    introZh: "Felix Heikka 在 Hacker News 写下这段经历时，产品已经有 4000 多名用户。他把时间拨回最前面。两个人，没有广告预算，也没有现成受众。他们去目标 subreddit 发了几次调查，承诺认真看参与者的项目，再用自己的反馈换对方回答问题。最后只有 8 到 10 位创始人愿意聊。\n\n这批人很少，却足够让团队决定先做下去。MVP 完成后，他们把产品发回给参与者。Felix 自报两周内到了 100 名用户。后来他又公开过 4000 多名用户、100 多名付费客户和 2300 美元月经常性收入，评论区有人拿旧帖核对数字，他也回来解释收入和 MRR 的口径。案例的价值正在这里。结果有人质疑，原帖没有把质疑藏起来。",
    introEn: "When Felix Heikka wrote this account on Hacker News, the product already had more than 4,000 users. He rewound to the beginning. Two people, no advertising budget, and no existing audience. They posted a survey several times in target subreddits and promised to review participants' projects in exchange for honest answers. Only eight to ten founders took part.\n\nThat small group was enough for the team to keep building. When the MVP was ready, they sent it back to the participants. Felix reports reaching 100 users in two weeks. He later published more than 4,000 users, 100 paying customers, and $2,300 MRR. Commenters compared those figures with older posts, and he returned to explain the difference between revenue and MRR. The challenge remains visible in the original record.",
    sectionsZh: [
      { heading: "那 8 到 10 个人先给了团队一套真话", body: "调查问的是目标用户正在经历什么，也问他们会不会采用团队设想的办法。Felix 没有说大家一发帖就涌进来。他在评论里补了一句，帖子要去几个不同社区发几次，愿意回答的人也需要一点交换。团队付出的东西是时间，他们认真看对方的项目。\n\nMVP 发出去以后，并非每位参与者都成了活跃用户。Felix 后来明确承认这一点。需求验证给出的只是继续做的理由，还没有给出一个稳定生意。这个预期更接近普通团队能拿到的结果。", pullQuote: "" },
      { heading: "两周到 100 人以后，后面的数字开始变得复杂", body: "Felix 说 Product Hunt 上线当天带来 475 名新用户，一周左右做到 1000 人。五个月回看时，他列出 4000 多名用户、100 多名付费客户和 2300 美元 MRR。\n\n评论者随后翻出旧帖，质疑他曾经使用过不同的收入数字。Felix 回来解释，一次性收入和月经常性收入用了不同口径。我们无法替任何一方做审计。能保留下来的结论只有过程。调查、回访和产品改进确实按这个顺序被公开写下。", pullQuote: "" },
      { heading: "哥飞把用户说过的话接到了一个搜索页面上", body: "另一个案例从页面往回找问题。哥飞在 V2EX 拆 voiceisolator.io，先看搜索结果里的竞争，再打开首页逐项检查。Title 带核心词，description 继续解释，canonical 指向正确地址。页面约有 1755 个英文单词，H2、图文教程和 FAQ 都围绕声音分离。\n\n这份拆解没有证明 Google 为什么给它排名。它提供了一条能看见的编辑线索。用户搜的任务出现在标题里，首屏接住，教程教人完成，FAQ 处理剩下的疑问。页面很长，每一段仍得回到同一件事。", pullQuote: "" },
      { heading: "七天能验证的只是一小块", body: "先找 8 到 10 位目标用户，收下他们描述同一麻烦时用过的话。选出重复最多的一句，放进 Title、H1 和首屏答案，再补一个能走完的教程。第七天请参与者回来看看，他们能不能一眼认出自己的问题。\n\n搜索结果不会在七天里给出稳定排名。第一轮只看页面有没有被理解，参与者愿不愿意继续试。四周后仍没有展示，再查索引和关键词。已经有展示却没人点击，标题需要改。有人点击却没人使用，页面没有把承诺做完。", pullQuote: "" }
    ],
    sectionsEn: [
      { heading: "Eight to ten people gave the team a small body of honest language", body: "The survey asked what target users were experiencing and whether they would adopt the proposed solution. Felix does not describe an effortless rush of responses. In a comment, he says the post needed several attempts across communities, and the exchange mattered. The team spent time reviewing other people's projects.\n\nNot every participant became an active user after the MVP arrived. Felix later says so directly. Validation produced a reason to continue, not a stable business. That expectation is closer to what an ordinary team can use.", pullQuote: "" },
      { heading: "After the first 100, the numbers became more complicated", body: "Felix reports 475 new users on Product Hunt launch day and roughly 1,000 within a week. At five months, he listed more than 4,000 users, over 100 paying customers, and $2,300 MRR.\n\nA commenter found older posts and questioned the revenue figures. Felix returned to distinguish one-time revenue from monthly recurring revenue. This article cannot audit either side. The durable part is the publicly documented sequence of survey, follow-up, and product improvement.", pullQuote: "" },
      { heading: "Ge Fei carried the user's language into a search page", body: "The second case works backward from the page. In a V2EX teardown of voiceisolator.io, Ge Fei looked at competition and then inspected the homepage. The title carried the core term, the description continued it, and the canonical pointed correctly. About 1,755 English words, H2s, a visual tutorial, and FAQs stayed around voice isolation.\n\nThe teardown does not prove why Google ranked the site. It supplies an editorial line we can inspect. The query appears in the title, the opening answers it, the tutorial completes the task, and the FAQ handles what remains.", pullQuote: "" },
      { heading: "Seven days can validate only a small piece", body: "Find eight to ten target users and save how they describe the same problem. Put the most repeated phrase into the title, H1, and opening answer, then add one complete tutorial. On day seven, ask participants whether they recognize their problem on the page.\n\nSearch will not provide stable ranking evidence in a week. The first cycle asks whether people understand the page and want to keep trying. After four weeks, no impressions point to indexing or query fit. Impressions without clicks point to the title. Clicks without use point to an unfinished answer.", pullQuote: "" }
    ],
    experimentTitleZh: "七天把十句话变成一页答案", experimentTitleEn: "Turn ten customer phrases into one answer page",
    experimentsZh: [{ label: "01 / 收十句话", body: "保存目标用户描述同一麻烦的原话。" }, { label: "02 / 改五个位置", body: "更新 Title、H1、首屏、教程和 FAQ。" }, { label: "03 / 找三人复核", body: "让参与者判断页面是否回答原问题。" }],
    experimentsEn: [{ label: "01 / COLLECT TEN PHRASES", body: "Save target users' wording for one repeated problem." }, { label: "02 / EDIT FIVE AREAS", body: "Update title, H1, opening answer, tutorial, and FAQ." }, { label: "03 / ASK THREE PEOPLE", body: "Have participants judge whether the page answers the original problem." }],
    caseStudies: [
      { subjectName: "哥飞", product: "voiceisolator.io 公开 SEO 拆解", timeframeZh: "2025 年 7 月公开帖子", timeframeEn: "Public post from July 2025", verificationZh: "公开创作者拆解", verificationEn: "Named public teardown", goalZh: "解释工具页为何获得搜索流量", goalEn: "Explain why a tool page earns search traffic", actionsZh: ["查竞争外链", "检查标题和描述", "核 canonical", "拆 H2、教程与 FAQ"], actionsEn: ["Checked competing links", "Inspected title and description", "Verified canonical", "Reviewed H2s, tutorial, and FAQ"], resultZh: "记录首页约 1755 个英文单词，并认为内容始终围绕核心词", resultEn: "Recorded roughly 1,755 English words and found the page stayed around the core query", failureZh: "这份创作者分析不能确认 Google 的具体排名原因", failureEn: "This is a creator analysis, not Google's confirmation of ranking causality", sourceUrl: "https://global.v2ex.com/t/1145904" },
      { subjectName: "Felix Heikka", publicHandle: "felixheikka", timeframeZh: "MVP 后两周至上线约五个月", timeframeEn: "From two weeks after MVP through roughly five months", verificationZh: "公开账号自述", verificationEn: "Public-handle firsthand", goalZh: "验证需求并获得前 100 用户", goalEn: "Validate demand and reach the first 100 users", actionsZh: ["发目标调查", "用项目反馈换回答", "给参与者发 MVP", "依据反馈改产品"], actionsEn: ["Posted a target survey", "Traded project feedback for responses", "Sent the MVP to participants", "Improved the product from feedback"], resultZh: "自报两周 100 用户，后续 4000 多用户、100 多付费和 2300 美元 MRR", resultEn: "Self-reported 100 users in two weeks, later 4,000 users, 100 paying, and $2,300 MRR", failureZh: "评论区质疑旧帖数字与发帖频率，本人解释收入与 MRR 口径", failureEn: "Comments challenged earlier figures and posting frequency; Felix explained revenue versus MRR", sourceUrl: "https://news.ycombinator.com/item?id=42821678" }
    ],
    sources: [
      { titleZh: "哥飞的 voiceisolator SEO 拆解", titleEn: "Ge Fei's voiceisolator SEO teardown", url: "https://global.v2ex.com/t/1145904", kind: "named-firsthand", publishedAt: "2025-07-25", accessedAt, supportsZh: "支撑 Title、description、canonical、1755 个单词、H2、教程和 FAQ 观察。", supportsEn: "Supports observations on title, description, canonical, 1,755 words, H2s, tutorial, and FAQ." },
      { titleZh: "Felix 的五个月增长复盘", titleEn: "Felix's five-month growth retrospective", url: "https://news.ycombinator.com/item?id=42821678", kind: "public-handle-firsthand", publishedAt: "2025-01-25", accessedAt, supportsZh: "支撑调查步骤、用户数字、Product Hunt 结果与评论质疑。", supportsEn: "Supports survey steps, user figures, Product Hunt results, and comment challenges." }
    ]
  },
  {
    slug: "content-compounding-founder-system", publishedAt: "2026-08-19", updatedAt: "2026-08-24", platform: "Founder Content", readingMinutes: 9, authorZh, authorEn,
    disclosureZh: "实名访谈与公司历史复盘 · Josh Ho 的工作流来自 Buffer 访谈。70 万读者和 150 万月访问是 Buffer 在 2013 与 2017 年披露的历史数据。",
    disclosureEn: "Named interview and company retrospectives · Josh Ho's workflow comes from a Buffer interview. The 700K readers and 1.5M monthly visits are historical Buffer figures published in 2013 and 2017.",
    titleZh: "Josh Ho 说自己算不上创作者，他每周只管把做过的事讲清楚", titleEn: "Josh Ho Does Not Think of Himself as a Creator. He Documents the Work He Already Does",
    seoTitleZh: "创始人内容系统真人案例｜Josh Ho 与 Buffer 百万访问博客", seoTitleEn: "Founder Content System Cases from Josh Ho and Buffer",
    descriptionZh: "一次官网改版，后来去了两档播客、一封通讯和一段视频。Josh 的办法很笨，也很适合没空追热点的创始人。",
    descriptionEn: "One homepage redesign later appeared across two podcasts, a newsletter, and a video. Josh's method is plain and well suited to founders who cannot chase trends all day.",
    seoDescriptionZh: "两个真人内容增长案例还原重复问题、固定录制、内容看板、每周发布节奏、平台改编、旧文更新和业务指标的具体做法、历史结果、适用边界与复盘方法等。",
    seoDescriptionEn: "Two real cases detail repeated-question notes, scheduled recording, editorial cadence, platform adaptation, old-post relaunches, and business metrics.",
    kickerZh: "增长案例 16 · 内容从正在做的工作里长出来", kickerEn: "GROWTH CASE 16 · CONTENT GROWS FROM WORK ALREADY UNDERWAY",
    introZh: "Buffer 的访谈开头先问 Josh Ho 怎样看待创作者这个身份，他的反应有点迟疑。Josh 更习惯把自己叫作创业者。Referral Rock 要做产品，也要获客，他还有两档播客和一封通讯。内容顺着这些工作往外长。\n\n这句话落到具体事情上，办法出奇地省力。创业者把同一个问题问到第三次，他就把回答记下来。公司要改官网，他顺手把过程放进营销播客，又在另一档播客里帮搭档改网站。那次工作后来变成一段视频、一封通讯和一集节目。四份内容共用一段真实经历，谁也不用临时编故事。",
    introEn: "Buffer's interview opens by asking Josh Ho how he relates to the creator label. He hesitates. Founder feels more natural. Referral Rock still needs product work and customer acquisition, while he also runs two podcasts and a newsletter. Content grows out of those jobs.\n\nThe method becomes unusually economical in practice. When founders ask the same question repeatedly, Josh records the answer. When the company redesigns its homepage, he discusses the process on a marketing podcast and helps a cohost with a site on another show. The work later becomes a video, a newsletter, and a podcast episode. Four assets share one lived source, so none needs an invented story.",
    sectionsZh: [
      { heading: "他先收下那些反复出现的问题", body: "Josh 和其他创业者聊天时，会留意同一个问题出现了几次。问的人多了，他就把几次回答合在一起，整理成笔记。笔记有时去 Twitter，有时留到播客里慢慢讲。读者已经在提问，选题会轻松很多。\n\n访谈发布时，他在 Twitter 有超过 1.7 万关注者。这个数字没有证明哪一条笔记带来了多少收入。它能说明一件较小的事。长期回答同一群人的具体问题，确实可以积出一批愿意继续听的人。", pullQuote: "" },
      { heading: "一次官网改版，刚好够他讲四次", body: "官网本来就要改，课程也已经买了。Josh 在营销播客里讲自己学到的东西，又在另一档创始人播客里现场帮搭档看网站。录制内容随后剪成视频，放进通讯，还作为播客节目继续发布。\n\n四份内容的入口不同，里面那件事没有变。官网哪里难改，课程怎样影响决定，现场给了什么建议，这些都来自已经发生的工作。复用在这里省下的是重新找题的时间，不会凭空多出四段经历。", pullQuote: "" },
      { heading: "Buffer 把这种偶然做成编辑部的日常", body: "Josh 的做法适合个人。Buffer 在 2013 年公开过团队版流程。想法先放进 Trello，每周从里面挑文章，研究任务跟着段落走。团队当时称博客每月约有 70 万读者，每周会做五篇内容。\n\n四年后的复盘里，节奏已经慢到每周两篇新文章，再加播客笔记。团队发现发得太多会拖累质量，还会更新旧文。一篇工具文章更新截图、结构和案例以后，日访问据称从约 300 涨到 700。70 万读者和 150 万月访问来自不同年份，放不到一张增长曲线上。", pullQuote: "" },
      { heading: "普通团队可以期待一条更短的链", body: "先别给自己定每天三条的任务。用一周收一个反复出现的问题，写一页完整回答，再录二十分钟对话。社交帖子取一个最具体的判断，邮件把过程讲完整。所有版本都回到同一份事实底稿。\n\n第一轮只看有没有人继续行动。有人回复，有人订阅，或者有人带着具体问题进入产品，都算信号。只有浏览，没有后续动作，先检查这个问题和业务有没有关系。Josh 的故事没有给出一条内容到收入的归因链，我们也不替他补。", pullQuote: "" }
    ],
    sectionsEn: [
      { heading: "He keeps the questions that return", body: "Josh notices when the same founder question appears in several conversations. He combines earlier answers into notes. A note may move to Twitter or wait for a longer podcast discussion. The audience has already asked for the subject.\n\nAt the time of the interview, he had more than 17,000 Twitter followers. That number does not attribute revenue to a particular note. It supports a smaller observation. Answering a specific group consistently can build an audience willing to keep listening.", pullQuote: "" },
      { heading: "One homepage redesign gave him four things to publish", body: "The homepage already needed work, and Josh had already taken a course. He discussed the lessons on a marketing podcast and then helped a cohost review a site on another founder show. The recording became a video, a newsletter item, and a podcast episode.\n\nEach format had a different entry point, while the event stayed fixed. Repurposing saved the search for a new subject. It did not manufacture four experiences.", pullQuote: "" },
      { heading: "Buffer turned the habit into editorial work", body: "Josh's method fits an individual. Buffer published a team process in 2013. Ideas entered Trello, weekly selection chose the next articles, and research tasks followed the sections. The company then reported roughly 700,000 monthly readers and five weekly pieces.\n\nBy a 2017 retrospective, the cadence had slowed to two new articles plus podcast notes each week. The team said higher volume had reduced quality, and it also relaunched old posts. One refreshed tools article reportedly moved from about 300 to 700 daily visits. The 700K-reader and 1.5M-visit figures come from different years and should not be placed on one clean growth curve.", pullQuote: "" },
      { heading: "A small team can expect a shorter chain", body: "Start with one repeated question in a week. Write a complete answer and record a 20-minute conversation. Let the social post carry one concrete judgment, while the email keeps the fuller sequence. Every version returns to the same factual source.\n\nThe first cycle needs only evidence of continued action. A useful reply, subscription, or specific product question counts. Visits with no next action may indicate that the subject is weakly connected to the business. Josh's interview does not provide content-to-revenue attribution, so this article does not invent it.", pullQuote: "" }
    ],
    experimentTitleZh: "七天把一个重复问题做成四份内容", experimentTitleEn: "Turn one repeated question into four assets in seven days",
    experimentsZh: [{ label: "01 / 收一个真问题", body: "只选本周被问过至少三次的问题。" }, { label: "02 / 留一份母稿", body: "写完整答案并保存事实与来源。" }, { label: "03 / 改三种媒介", body: "做播客讨论、社交帖和邮件，分别记录结果。" }],
    experimentsEn: [{ label: "01 / CAPTURE ONE QUESTION", body: "Choose a question asked at least three times this week." }, { label: "02 / KEEP ONE SOURCE", body: "Write the full answer and preserve its facts and references." }, { label: "03 / ADAPT THREE WAYS", body: "Create a podcast discussion, social post, and email, then track each outcome." }],
    caseStudies: [
      { subjectName: "Josh Ho", product: "Referral Rock", timeframeZh: "Buffer 于 2023 年发布访谈", timeframeEn: "Buffer interview published in 2023", verificationZh: "实名第一手访谈", verificationEn: "Named firsthand interview", goalZh: "让创始人日常工作持续产出内容", goalEn: "Turn founder work into sustainable content", actionsZh: ["记录重复问题", "整理成笔记", "固定录播客", "跨平台改编"], actionsEn: ["Captured repeated questions", "Compiled answers into notes", "Recorded on a schedule", "Adapted across platforms"], resultZh: "一次官网改版被做成四份内容，访谈时其 Twitter 关注超过 1.7 万", resultEn: "One homepage project became four assets; the interview reported more than 17K Twitter followers", failureZh: "访谈没有把每份内容与 Referral Rock 收入做直接归因", failureEn: "The interview does not directly attribute Referral Rock revenue to each asset", sourceUrl: "https://buffer.com/resources/creators-unlocked-josh-ho/" },
      { subjectName: "Buffer 内容团队", product: "Buffer Blog", timeframeZh: "2013 与 2017 年历史复盘", timeframeEn: "Historical retrospectives from 2013 and 2017", verificationZh: "公司自报", verificationEn: "Company-reported", goalZh: "把博客做成长期获客渠道", goalEn: "Build the blog into a durable acquisition channel", actionsZh: ["Trello 管选题", "按周选择与编辑", "为平台改编", "更新旧文"], actionsEn: ["Managed ideas in Trello", "Selected and edited weekly", "Adapted for platforms", "Relaunched old posts"], resultZh: "历史自报从约 70 万月读者增长到超过 150 万月访问", resultEn: "Historical self-report grew from roughly 700K monthly readers to more than 1.5M monthly visits", failureZh: "指标来自不同年份与口径，不能代表 2026 年现状", failureEn: "Metrics use different years and definitions and do not represent 2026 performance", sourceUrl: "https://buffer.com/resources/buffer-blog-one-million/" }
    ],
    sources: [
      { titleZh: "Josh Ho 的创始人内容访谈", titleEn: "Josh Ho founder-content interview", url: "https://buffer.com/resources/creators-unlocked-josh-ho/", kind: "named-firsthand", publishedAt: "2023-05-25", accessedAt, supportsZh: "支撑重复问题、固定录制、官网改版四份内容和工具流程。", supportsEn: "Supports repeated questions, scheduled recording, four homepage assets, and the tool workflow." },
      { titleZh: "Buffer 70 万月读者流程复盘", titleEn: "Buffer's 700K monthly readers workflow", url: "https://buffer.com/resources/how-we-manage-a-blog-with-700000-readers-per-month/", kind: "company-reported", publishedAt: "2013-09-10", accessedAt, supportsZh: "支撑 Trello、每周五篇、研究、编辑和标题测试流程。", supportsEn: "Supports Trello, five weekly posts, research, editing, and headline testing." },
      { titleZh: "Buffer 150 万月访问历史复盘", titleEn: "Buffer's historical 1.5M monthly visits retrospective", url: "https://buffer.com/resources/buffer-blog-one-million/", kind: "company-reported", publishedAt: "2017-07-27", accessedAt, supportsZh: "支撑发布节奏、平台改编、邮件流量、旧文更新和业务指标。", supportsEn: "Supports cadence, platform adaptation, email traffic, content relaunches, and business metrics." }
    ]
  },
  ...seoXiaohongshuCaseStudyPosts
];
